### ISSUE TITLE
[Bug]No se puede borrar una organizacion

### ISSUE THREAD

**Issue by maximilianofni** [katalon-studio/katalon-testops#103]
- Katalon Studio Version: 7.2.1
- OS Version:
- Browser Version: 

Steps to Reproduce:

1. Ingresar  https://analytics.katalon.com/home
2. Ingresar a un Organismo.
3. se podria agregar la opcion eliminar un Organismo

Expected behavior: 

Screenshots:

**Comment by Padoplin** [comment]
Hello there!

Currently, we do not support removing an Organization (it's is intended behavior, not a bug). However, we consider putting "Remove an Organization" in our product backlog in the future.

Thank you for your opinion.

Padoplin.

**Comment by maximilianofni** [comment]
de nada , saludos

**Comment by linhhuynhtruc** [comment]
Hi @maximilianofni,

This feature is now available. Please refer to [this document](https://docs.katalon.com/katalon-analytics/docs/setup-org-team-project.html#delete-an-organization) for more details.

Thank you.
