### ISSUE TITLE
Bulk Download Test Results from TestOps

### ISSUE THREAD

**Issue by Asht3ch** [katalon-studio/katalon-testops#107]
Is there a way we could download multiple test results in a single click to a .csv, rather than opening each test result individually?

Thanks

**Comment by linhhuynhtruc** [comment]
Hi,

Hi there

This feature is currently not supported in Katalon TestOps. We will consider putting this feature in our product backlog in the future.

Thank you for your suggestion!

**Comment by linhhuynhtruc** [comment]
Hi,

This feature is now available in TestOps. Please check it out and refer to [this document](https://docs.katalon.com/katalon-analytics/docs/project-management-delete.html#delete-an-execution) for instructions.

Thank you.
