### ISSUE TITLE
License Usage Tracking

### ISSUE THREAD

**Issue by Padoplin** [katalon-studio/katalon-testops#109]
Are there any plans to allow tracking of # of concurrent sessions over time (say being able to see the max # of concurrent sessions by hour for the past week) as part of the TestOps web console?

This is likely to be critical for our team to be able to track license utilization over time and make / justify budgeting for advance adjustments based on usage patterns (i.e. - detecting if we're close to using max # of concurrent licenses, for example).

Source: https://katalon.zendesk.com/agent/tickets/886

**Comment by linhhuynhtruc** [comment]
This feature is now available.
