### ISSUE TITLE
Katalon Studio free license

### ISSUE THREAD

**Issue by hotkirk** [katalon-studio/katalon-testops#117]
Hello,
I tried Katalon Studio 7 with a 30 day test license.
now, this license on an non connected PC is expired.

How can I get an offline license for Katalon Studio (not Katalon Studio Enterprise) for my PC, that ist not connected to the internet.
What steps are necceary?

**Comment by Padoplin** [comment]
Hello there

Offline mode is not available for free license of Katalon Studio. If you'd like to use offline mode, please subscribe to Katalon Studio Enterprise's annual node-locked license.

Jass
