### ISSUE TITLE
Licence activation issues with KRE - Unexpected response URL: https://analytics.katalon.com/info Status: 503

### ISSUE THREAD

**Issue by danieltheaxe** [katalon-studio/katalon-testops#119]
Note registered machine ID removed before trying.

INFO: Katalon Version: 7.5.5
INFO: Katalon TestOps server URL: https://analytics.katalon.com
INFO: Katalon Store server URL: https://store.katalon.com
INFO: Java vendor: Oracle Corporation
INFO: Java version: 1.8.0_181
INFO: Local OS: Mac OS X 64bit
INFO: CPU load: 0%
INFO: Total memory: 16384 MB
INFO: Free memory: 2711 MB

Activating...
Start activating offline...
Search for valid offline licenses in folder: /Users/server/.katalon/license
The number of valid offline licenses: 0
Offline activation failed.
Start activating online...
**Katalon TestOps: Unexpected response, URL: https://analytics.katalon.com/info, Status: 503, Response: 
Cannot connect to Katalon TestOps server. Please check your Internet connection and try again.
All launchers terminated**

Steps to Reproduce:

1. Run a test suite using KRE

Expected behavior: 
Licence to be activated

**Comment by danieltheaxe** [comment]
I have worked around this by creating an offline licence, but this is not ideal.

**Comment by linhhuynhtruc** [comment]
Hi @danieltheaxe,

This happened due to the downtime of the TestOps server during our maintenance process. Can you try again and let us know if it still happens?

**Comment by danieltheaxe** [comment]
Will do thanks.

--
*Daniel de Byl*
QA and Automation Developer
Desygner desygner.com <https://www.desygner.com/>
We Brand webrand.com <https://www.webrand.com/>
