### ISSUE TITLE
Filtering of Test Case Executions by Profile

### ISSUE THREAD

**Issue by MichalMucek** [katalon-studio/katalon-testops#121]
At `https://analytics.katalon.com/team/<team-id>/project/<project-id>/test-design/test-cases/<test-case-id>-<test-case-name>` I can view the history of a test case and I can filter it by name, status, test suite's name and timespan. What's missing, I'd say, is filtering by execution profile.

Please, add filtering by execution profile for test case history and possibly, to test suite history as well.

**Comment by linhhuynhtruc** [comment]
Hi @MichalMucek,

Thank you for your suggestion.

This feature is now available in Katalon TestOps. Please check it out.

Cheers,
Linh Huynh
