### ISSUE TITLE
Cucumber Index.html is blank when opened via Download Files Button from Executions in Katalon testOps

### ISSUE THREAD

**Issue by bobhaghotmail** [katalon-studio/katalon-testops#126]
katalon-testops 
- Katalon Studio Version: 7.6.6
- OS Version: Win 10 64bit
- Browser Version: Version 85.0.4183.121

Steps to Reproduce:

So when you run a suite with BDD Tests.
and you open the report Locally - in that report there is a folder for cucumber report
and index.html
in the html folder locally there are other files

when you click index.html
![image](https://user-images.githubusercontent.com/10762658/94859277-20f32100-03e9-11eb-8bd3-47d5d2d0acda.png)

You can see the Report (Good)
![image](https://user-images.githubusercontent.com/10762658/94858887-8e528200-03e8-11eb-8015-4c8531053376.png)

But if you go to Katalon testOps

https://analytics.katalon.com/team/1303/project/72908/executions/4

And click on Download Files Button

![image](https://user-images.githubusercontent.com/10762658/94858666-3e73bb00-03e8-11eb-9346-b1fcdfaa0e25.png)

If you go into the (html) folder
there is only 1 file  index.html
![image](https://user-images.githubusercontent.com/10762658/94858989-b215c800-03e8-11eb-936f-bb8b41e8a40c.png)

When you click it.  you can't see the cucumber report

Expected behavior: 
When downloading the Execution files from  Katalon testOps, the user should be able to open/display Cucumber Report index.html

Current behavior:
you get a blank page.

**Comment by devalex88** [comment]
Hi @bobhaghotmail,

Thank you for the feedback. This issue has been fixed in Katalon Studio 7.7.1. Please try the new version and let me know the result.
