### ISSUE TITLE
Everytime a failed test report is imported into Katalon we get an email[Bug]

### ISSUE THREAD

**Issue by DesiganPillay** [katalon-studio/katalon-testops#130]
- Katalon Studio Version: N/A
- OS Version: n/a
- Browser Version: n/a

Steps to Reproduce: import a test report into katalon analytics

1.
2.

Expected behavior: the ability switch off all notifications, currently can only switch off notifications or passed test results

Screenshots:

**Comment by linhhuynhtruc** [comment]
Hi @DesiganPillay,

Thank you for your suggestion.

We have put this feature into our backlog and will keep you informed once it's ready.

Cheers,
Linh Huynh
