### ISSUE TITLE
[Bug] Expired schedule job triggered along with other scheduled job

### ISSUE THREAD

**Issue by Rampraesath** [katalon-studio/katalon-testops#134]
- Katalon Studio Version: 7.5.5
-KRE Version: 7.5.5
- OS Version: Mac Os Catalina 10.15.5
- Browser Version: Google Chrome 86.0.4240.80

Steps to Reproduce:

1. Connect Git project[Project - 1] to Katalon Test Ops
2. Create a test plan[TP- 1] in Test Ops with Katalon command referring to a test suite collection [TSC - 1]
3. Create a schedule for test plan created in step 2 above which expires in 48 hours. ***Keep the schedule in active state after expiry***
4. After 48 hours, on a new PROJECT[Project - 2], follow step 1 up to step 2
5. Create a schedule for test plan in [Project - 2] and wait for execution

Expected behavior: 
-Job scheduled in [Project -2] should be executed

Actual behaviour"
-Expired job in [Project - 1] gets triggered along with [Project - 2]'s job

Screenshots:
![Test Schedule](https://user-images.githubusercontent.com/10155258/96535578-af5e1280-12c4-11eb-83fb-2c20b4d3005c.png)
![Test Plan](https://user-images.githubusercontent.com/10155258/96535589-b2f19980-12c4-11eb-82a3-29b15a3b2c8a.png)

**Comment by thongmgnguyen** [comment]
Hi @Rampraesath,
It's an issue in our schedule feature. We will get it fixed soon. Thank you for your contribution.
