### ISSUE TITLE
Can't generate api key

### ISSUE THREAD

**Issue by buenaandawc** [katalon-studio/katalon-testops#160]
- Katalon Studio Version:
- OS Version:
- Browser Version:

Steps to Reproduce:

1.
2.

Expected behavior: 

![image](https://user-images.githubusercontent.com/79564599/113234751-71820300-92d4-11eb-922b-a2bd3c9ee9c6.png)

**Comment by thongmgnguyen** [comment]
Could you give me your email to verify this issue?

**Comment by buenaandawc** [comment]
***@***.***
[image: wc-logo.png]

*Buena Garcia Anda*
Software QA, White Cloak Technologies, Inc.

(+63)  <+63+927+907+1805>9271819134 | ***@***.***
***@***.***>

www.whitecloak.com

**Comment by buenaandawc** [comment]
buena.anda@exploretale.com
