### ISSUE TITLE
Flaky test case list should include maintainer

### ISSUE THREAD

**Issue by jimsears** [katalon-studio/katalon-testops#161]
Please search existing issues to avoid creating duplicates. 
I searched for issues on flaky and did not find any.

 Describe the feature you'd like. 
Test Case report for "Flaky" tests needs additional column to hold tester accountable to correct test failures. The test list is not enough information to take action. My old boss told me "All reports should be actionable". If the report doesn't bring about change then does the report add value?

Thanks!
Jim

![image](https://user-images.githubusercontent.com/64658031/113803737-ba95e500-9722-11eb-9731-7ef034c22306.png)

**Comment by nhmy** [comment]
@jimsears Thank you for your feedback. We have added this to our backlog and would consider it for future release.

**Comment by nhmy** [comment]
Hi @jimsears. We have added the maintainer column in the Flaky test list. Thank you for your request and let me know if you have any more questions!

**Comment by jimsears** [comment]
Thank you!

Sincerely,
Jim

214.923.1455
***@***.***
________________________________

**Comment by jimsears** [comment]
Thank you!
