### ISSUE TITLE
Visual Testing enhancement

### ISSUE THREAD

**Issue by cs30507** [katalon-studio/katalon-testops#175]
Is katalon planning to provide enhanced visual testing capabilities similar to applitools on TestOps
1. Different matching algorithm (Exact, Strict, layout) etc.. 
2. Ignore region feature 
3. Ignore displaced elements feature.

**Comment by nhmy** [comment]
@cs30507 Hi! We do have plan to enhance our visual testing capabilities, however, it won't be available this year. We're working hard to make it happen so keep an eye out :) thank you for your support.
