### ISSUE TITLE
I'm not getting test results into my test executions [Bug]

### ISSUE THREAD

**Issue by jmelendereloquest** [katalon-studio/katalon-testops#178]
When running my test collections in my remote docker I'm not getting the expected results on Katalon/testOps

- Katalon Studio Version: 7.9.1
- OS Version: Docker
+ echo 'Starting Katalon Studio'
Starting Katalon Studio
+ cat /katalon/version
Mozilla Firefox 85.0
Google Chrome 88.0.4324.150 
Katalon Studio

Steps to Reproduce:

1. Run my remote test colections

Actual Result: some test executions does't have test result details, some others even doesn't show up

After running 5 different collection I only get 3 result, 2 of them empty and 1 is stuck (like it didn't finish) but the actual test it finished 1 hour ago.

![image](https://user-images.githubusercontent.com/87989429/127011732-b96c3b57-5e04-48d3-84c2-e1f9440c63e3.jpeg)

https://analytics.katalon.com/team/16227/project/39497/executions/7342

**Comment by quidl** [comment]
Hi @jmelendereloquest 
Sorry for the late reply. Please check again
The system was too busy at that time, so the operation was delayed longer than usual
