### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by sebafares1975** [katalon-studio/katalon-testops#194]
Description
session not created: This version of ChromeDriver only supports Chrome version 92 Current
browser version is 94.0.4606.61 with binary path

- Katalon Studio Version: 8.1.0
- OS Version: Windows 10 pro  Version 21H1
- Browser Version: Versión 94.0.4606.61 (Build oficial) (64 bits)
Steps to Reproduce:

1. cmd 
2. run command generate

Expected behavior:  testOps report

Screenshots:

**Comment by lieuhuynh1811** [comment]
Hi sebafares1975,
Your web driver version is out of date. In the console mode, you can use this command argument, --config -webui.autoUpdateDrivers=true, to allow WebDriver binaries to be updated automatically.
Thanks.
