### ISSUE TITLE
KRE License help required

### ISSUE THREAD

**Issue by mehmoodanjum** [katalon-studio/katalon-testops#196]
Currently we are using KSE license – floating.

Can you please guide me which license of KRE is suitable for us?
1-	We have configured Jenkins jobs for each test suite
2-	Now I want If I run a Jenkins job, it executes all relevant tests on backend in CLI mode. This same case will be for other suites/jobs
3-	Later I will configure only one job on Jenkins. It will execute all jobs parallelly in CLI mode.
4-	Later we want to make our script and execution part of CI/CD

Please suggest which is suitable KRE license for us in this case? I believe KRE floating is fine. But need your suggestions
1-	KRE Node locked
2-	KRE Floating 
3-	KRE devops

Regards
Mehmood

**Comment by mehmoodanjum** [comment]
instead of jenkins we are also using Agent inside testops. we configure an agent to execute tests

**Comment by nhmy** [comment]
Hello @mehmoodanjum 

Node-locked or Floating license depends on if you want it to be assigned to one machine ID or one execution session and shared across multiple machines. You can take a look at this document for more details: 
https://docs.katalon.com/katalon-studio/docs/license.html#license-types

If you still have questions, please let me know and I'm happy to assist further.

My Nguyen
