### ISSUE TITLE
On Katalonc Error reloading plugins...

### ISSUE THREAD

**Issue by mguerrer** [katalon-studio/katalon-testops#197]
Hi.     I am running a test suite using Katalonc.    In my machine I have Katalon Studio that I used to generate the command line.   If I execute locally with IDE or Katalonc it runs smoothly.
However when I execute the same command from Gitlab pipeline occurs this error reloading plugins.    Can you please help me?

**This is the content of Error log: C:/Users/marcos.guerrero/AppData/Local/Temp/session-69792edd/.metadata/.log**
katalon.versionNumber=8.1.0
katalon.buildNumber=208
!SESSION 2021-11-02 09:40:27.378 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_282
java.vendor=Azul Systems, Inc.
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -runMode=console -projectPath=C:\Gitlab\admin_automation\Admin.prj -retry=0 -testSuiteCollectionPath=Test Suites/Test Plans/Regression-QA -apiKey=adc4b56c-4c5a-4dc8-906e-18fec3db8f9b -testOpsProjectId=218986 --config -proxy .auth.option=NO_PROXY -proxy .system.option=NO_PROXY -proxy .system.applyToDesiredCapabilities=true -webui .autoUpdateDrivers=true
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -data @noDefault -runMode=console -projectPath=C:\Gitlab\admin_automation\Admin.prj -retry=0 -testSuiteCollectionPath=Test Suites/Test Plans/Regression-QA -apiKey=adc4b56c-4c5a-4dc8-906e-18fec3db8f9b -testOpsProjectId=218986 --config -proxy .auth.option=NO_PROXY -proxy .system.option=NO_PROXY -proxy .system.applyToDesiredCapabilities=true -webui .autoUpdateDrivers=true

!ENTRY org.eclipse.core.resources 2 10035 2021-11-02 09:42:18.529
!MESSAGE The workspace will exit with unsaved changes in this session.

**This is the full trace in console**
**$ C:\Katalon_Studio_Engine_Windows_64-8.1.0\katalonc -noSplash -runMode=console -projectPath="C:\Gitlab\admin_automation\Admin.prj" -retry=0 -testSuiteCollectionPath="Test Suites/Test Plans/Regression-QA" -apiKey="xxxxxxxxxxxxxxxxxxxxxx" -testOpsProjectId=218986 --config -proxy.auth.option=NO_PROXY -proxy.system.option=NO_PROXY -proxy.system.applyToDesiredCapabilities=true -webui.autoUpdateDrivers=true**
Katalon workspace folder is set to default location: C:\Users\MARCOS~1.GUE\AppData\Local\Temp\session-69792edd
Starting Groovy-Eclipse compiler resolver. Specified compiler level: unspecified
138 org.codehaus.groovy_2.4.20.v202009301404-e2006-RELEASE ACTIVE
INFO: Katalon Version: 8.1.0
INFO: Command-line arguments: -runMode=console -projectPath=C:\Gitlab\admin_automation\Admin.prj -retry=0 -testSuiteCollectionPath=Test Suites/Test Plans/Regression-QA -apiKey=******** -testOpsProjectId=218986 --config -proxy .auth.option=NO_PROXY -proxy .system.option=NO_PROXY -proxy .system.applyToDesiredCapabilities=true -webui .autoUpdateDrivers=true
INFO: User working dir: C:\GitLab-Runner\builds\eemU_JgL\0\wabtecone-platform\automation\admin_automation
INFO: Error log: C:/Users/marcos.guerrero/AppData/Local/Temp/session-69792edd/.metadata/.log
INFO: Katalon TestOps server URL: https://analytics.katalon.com
INFO: Katalon Store server URL: https://store.katalon.com
INFO: User home: C:\Users\marcos.guerrero
INFO: Java vendor: Azul Systems, Inc.
INFO: Java version: 1.8.0_282
INFO: Local OS: Windows 10 64bit
INFO: CPU load: 0%
INFO: Total memory: 16144 MB
INFO: Free memory: 9335 MB
Start getting machine ID on Windows
Start appending additional signatures
hardwareSerialNumber 
osDependentUsername marcos.guerrero
End appending additional signatures e5db5ef7-04c0-4ff4-aee3-bf22c5bec921__marcos.guerrero
End getting machine ID on Windows 9c62b54b628539b5db0372a06930d748
INFO: Machine ID: 9c62b54b628539b5db0372a06930d748
INFO: Your environment is compatible with the Katalon Runtime Engine NODE-LOCKED or FLOATING license. For a fixed machine ID, use a NODE-LOCKED license; for a dynamic machine ID, use a FLOATING license.
Activating...
Start activating offline...
Search for valid offline licenses in folder: C:\Users\marcos.guerrero\.katalon\license
The number of valid offline licenses: 0
Offline activation failed.
Start activating online...
Delete folder: bin
Delete folder: Libs
Cleaning up workspace
Opening project file: C:\Gitlab\admin_automation\Admin.prj
Generating global variables...
Parsing custom keywords...
Project 'Admin' opened
Start reloading plugins...
Tue Nov 02 09:40:59 CDT 2021
com.kms.katalon.activation.plugin.models.KStoreClientExceptionWithInfo: Invalid credentials.
	at com.kms.katalon.activation.plugin.service.KStoreRestClient.getLatestPlugins(KStoreRestClient.java:80)
	at com.kms.katalon.activation.plugin.service.PluginService.getOnlinePlugins(PluginService.java:315)
	at com.kms.katalon.activation.plugin.service.PluginService.reloadPlugins(PluginService.java:95)
	at com.kms.katalon.activation.plugin.handler.ConsoleModeReloadPluginsHandler.reload(ConsoleModeReloadPluginsHandler.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.kms.katalon.execution.console.ConsoleMain.reloadPlugins(ConsoleMain.java:555)
	at com.kms.katalon.execution.console.ConsoleMain.launch(ConsoleMain.java:479)
	at com.kms.katalon.console.application.ConsoleApplicationStarter.start(ConsoleApplicationStarter.java:37)
	at com.kms.katalon.application.Application.runConsole(Application.java:125)
	at com.kms.katalon.application.Application.start(Application.java:88)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1447)
Start check license task
chromedriver is located at default location: C:\Katalon_Studio_Engine_Windows_64-8.1.0\configuration\resources\drivers\chromedriver_win32\chromedriver.exe. In case your browser is updated to a newer version, please use this command to update chromdriver: --config -webui.autoUpdateDrivers=true
--------------------------RETRY EXECUTION INFORMATION--------------------------
Test Suite Collection 'Regression-QA':
- Test Suite 'Organization Management' runs with Immediately retry strategy and 0 retry time(s).
--------------------------------------------------------------------------------
Running: Test Suites/Features/Organization Management - Chrome - 20211102_094107
INFO: KATALON_JAVA_HOME: null
--------------------------------------------------------------------------------
Test Suites/Test Plans/Regression-QA - 20211102_094104...................0/2(0%)
--------------------------------------------------------------------------------
Test Suites/Features/Organization Management - Chrome - 20211102_094107..0/2(0%)
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
Test Suites/Test Plans/Regression-QA - 20211102_094104..................1/2(50%)
--------------------------------------------------------------------------------
Test Suites/Features/Organization Management - Chrome - 20211102_094107.1/2(50%)
--------------------------------------------------------------------------------
Launcher status after execution process completed: Running
Start writing execution.uuid file to folder: C:\Gitlab\admin_automation\Reports\20211102_094104\Features\Organization Management\20211102_094107
Start generating JUnit report folder at: C:\Gitlab\admin_automation\Reports\20211102_094104\Features\Organization Management\20211102_094107...
JUnit report were generated at folder: C:\Gitlab\admin_automation\Reports\20211102_094104\Features\Organization Management\20211102_094107
For real-time monitoring and better reporting capabilities please integrate this project with Katalon TestOps (more details at https://docs.katalon.com/katalon-analytics/docs/integration-with-katalon-studio.html#enable-integration)
Uploading report to Katalon TestOps...
Report has been sent to Katalon TestOps
--------------------------------------------------------------------------------
Test Suites/Test Plans/Regression-QA - 20211102_094104.................2/2(100%)
--------------------------------------------------------------------------------
Test Suites/Features/Organization Management - Chrome - 20211102_094107.........
.......................................................................2/2(100%)
--------------------------------------------------------------------------------
Preparing integration report for Katalon TestOps
Done preparing integration report for Katalon TestOps
Preparing integration report for Azure
Done preparing integration report for Azure
Preparing integration report for qTest
Done preparing integration report for qTest
Uploading report to Katalon TestOps...
Start sending test result to Katalon TestOps
Uploading log files of test suite collection
TestOps project is overridden to 218986
Sending file: C:\Gitlab\admin_automation\Reports\20211102_094104\Features\Organization Management\20211102_094107\20211102_094107.csv
Sending file: C:\Gitlab\admin_automation\Reports\20211102_094104\Features\Organization Management\20211102_094107\20211102_094107.html
Sending file: C:\Gitlab\admin_automation\Reports\20211102_094104\Features\Organization Management\20211102_094107\cucumber_report\1635864086339\cucumber.json
Sending file: C:\Gitlab\admin_automation\Reports\20211102_094104\Features\Organization Management\20211102_094107\cucumber_report\1635864086339\cucumber.xml
Sending file: C:\Gitlab\admin_automation\Reports\20211102_094104\Features\Organization Management\20211102_094107\cucumber_report\1635864086339\html\formatter.js
Sending file: C:\Gitlab\admin_automation\Reports\20211102_094104\Features\Organization Management\20211102_094107\cucumber_report\1635864086339\html\index.html
Sending file: C:\Gitlab\admin_automation\Reports\20211102_094104\Features\Organization Management\20211102_094107\cucumber_report\1635864086339\html\jquery-1.8.2.min.js
Sending file: C:\Gitlab\admin_automation\Reports\20211102_094104\Features\Organization Management\20211102_094107\cucumber_report\1635864086339\html\report.js
Sending file: C:\Gitlab\admin_automation\Reports\20211102_094104\Features\Organization Management\20211102_094107\cucumber_report\1635864086339\html\style.css
Sending file: C:\Gitlab\admin_automation\Reports\20211102_094104\Features\Organization Management\20211102_094107\cucumber_report\1635864086339\k-cucumber.json
Sending file: C:\Gitlab\admin_automation\Reports\20211102_094104\Features\Organization Management\20211102_094107\cucumber_report\1635864090938\cucumber.json
Sending file: C:\Gitlab\admin_automation\Reports\20211102_094104\Features\Organization Management\20211102_094107\cucumber_report\1635864090938\cucumber.xml
Sending file: C:\Gitlab\admin_automation\Reports\20211102_094104\Features\Organization Management\20211102_094107\cucumber_report\1635864090938\html\formatter.js
Sending file: C:\Gitlab\admin_automation\Reports\20211102_094104\Features\Organization Management\20211102_094107\cucumber_report\1635864090938\html\index.html
Sending file: C:\Gitlab\admin_automation\Reports\20211102_094104\Features\Organization Management\20211102_094107\cucumber_report\1635864090938\html\jquery-1.8.2.min.js
Sending file: C:\Gitlab\admin_automation\Reports\20211102_094104\Features\Organization Management\20211102_094107\cucumber_report\1635864090938\html\report.js
Sending file: C:\Gitlab\admin_automation\Reports\20211102_094104\Features\Organization Management\20211102_094107\cucumber_report\1635864090938\html\style.css
Sending file: C:\Gitlab\admin_automation\Reports\20211102_094104\Features\Organization Management\20211102_094107\cucumber_report\1635864090938\k-cucumber.json
Sending file: C:\Gitlab\admin_automation\Reports\20211102_094104\Features\Organization Management\20211102_094107\execution.properties
Sending file: C:\Gitlab\admin_automation\Reports\20211102_094104\Features\Organization Management\20211102_094107\execution.uuid
Sending file: C:\Gitlab\admin_automation\Reports\20211102_094104\Features\Organization Management\20211102_094107\execution0.log
Sending file: C:\Gitlab\admin_automation\Reports\20211102_094104\Features\Organization Management\20211102_094107\JUnit_Report.xml
Sending file: C:\Gitlab\admin_automation\Reports\20211102_094104\Features\Organization Management\20211102_094107\testCaseBinding
Sending file: C:\Gitlab\admin_automation\Reports\20211102_094104\Features\Organization Management\20211102_094107\tsc_id.txt
Sending file: C:\Gitlab\admin_automation\Reports\20211102_094104\Test Plans\Regression-QA\20211102_094104\20211102_094104.rp
Sending file: C:\Gitlab\admin_automation\Reports\20211102_094104\Test Plans\Regression-QA\20211102_094104\JUnit_Report.xml
Katalon TestOps: Start uploading report to Katalon TestOps server: https://analytics.katalon.com
--------------------------------------------------------------------------------
Test Suites/Test Plans/Regression-QA - 20211102_094104.................2/2(100%)
--------------------------------------------------------------------------------
Test Suites/Features/Organization Management - Chrome - 20211102_094107.........
.......................................................................2/2(100%)
--------------------------------------------------------------------------------
Katalon TestOps - Execution URL: https://analytics.katalon.com/from-ks/execution-result?teamId=207388&projectId=218986&id=15770291
End sending to Katalon TestOps
Report has been sent to Katalon TestOps
Uploading report to Azure...
Report has been sent to Azure
Uploading report to qTest...
Report has been sent to qTest
--------------------------------------------------------------------------------
Test Suites/Test Plans/Regression-QA - 20211102_094104.................2/2(100%)
--------------------------------------------------------------------------------
Test Suites/Features/Organization Management - Chrome - 20211102_094107.........
.......................................................................2/2(100%)
--------------------------------------------------------------------------------
NLS missing message: ConsoleMain_MSG_NON_DEVOPS_LICENSE_COMPATIBLITY in: com.kms.katalon.execution.constants.executionMessages
Execution completed. Exit code: 1.
Start clean up session
End check license task
End clean up session
Start release license task
License released
End release license task
All launchers terminated

**Comment by Prashu19a11** [comment]
Hi, my team is running Kataon Studio Enterprise Version 8.1.0.
We are also facing the same issue.
Execution is successful on local whereas code on Git Pipeline fails due to the above issue.

Any help would be much appreciated.

**Comment by nhmy** [comment]
Hi @mguerrer @Prashu19a11 pr

We have looked into the issue and it should be resolved now. Can you give it another try and let me know if the problem still persist? Thank you!

Best,
My

**Comment by MihirVhi** [comment]
Hi, 

Could you please confirm what done to resolve the issue, we are having the same issue
Execution is successful on local whereas on Jenkins Pipeline does not execute any tests and show message Launcher status after execution process completed: Running.

We are using  Kataon Studio Enterprise Version 8.6.0.

Thanks

Regards

Mihir

**Comment by tuananht** [comment]
Hi @MihirVhi,

Can you check the license of Katalon Runtime Engine and mark sure you can use this license?
And Katalon provides Katalon Jenkins plugin to execute tests in the Jenkins Pipeline, you can explore this plugin [here](https://plugins.jenkins.io/katalon/).

**Comment by MihirVhi** [comment]
Hi @tuananht,

Thanks for the response.

We are using the Katalon Jenkins plugin and also the Katalon Runtime Engine license..

Regards

Mihir
