### ISSUE TITLE
[Feature] Add Folder names to Testsuite names 

### ISSUE THREAD

**Issue by donauerpascal** [katalon-studio/katalon-testops#23]
We have a feature based branch. 
To analyse the healthiness of the single features it would be great if the testsuite name in Katalon Analytics could be filtered by the folders where the suites are sorted in. 
Otherwise you have to name the testsuite with the name of the folder_subfolder_subfolder_testname etc. which would be redundant and too long.

**Comment by linhhuynhtruc** [comment]
Hi @donauerpascal,

Thanks for your suggestion.
This feature is currently available and you can check it out. 
I will close the ticket now. For other bug reports or feature requests, please create a new one.

Cheers,
