### ISSUE TITLE
[Feature] Delete many reports from cloud and command Line

### ISSUE THREAD

**Issue by kelson-pereira** [katalon-studio/katalon-testops#24]
Dear Devs!

Uploading reports in Katalon Analytics after running the Test Suite or Test Suit Collection is a powerful feature.

However, with automating the execution of tests on the CI / CD, many reports will be loaded into Analytics by accumulating large volume of data from the step logs and screenshots.

It is currently possible to delete a report through the analytics interface on the cloud, but this is a manual process for each report.

The suggestion to better manage the volume of data in analytics could allow:

1. Delete many or all reports from the cloud in a few steps;
2. Delete one, many or all reports from the command line (for example using the JAR Katalon Studio Reports Uploader). A selection query with date criteria can be an initial filter. The functionality would be a good approach when automating CI / CD tests to manage this volume of data.

Regards,

**Comment by thongmgnguyen** [comment]
Hi @kelson-pereira,

It's a good idea. We will put it in our queue.

**Comment by kelson-pereira** [comment]
Thank you @thongmgnguyen,

I'm happy to contribute to this beautiful project.

Another possibility would be to include in the project preferences an option to automatically clear reports in Katalon Analytics cloud itself. For example:

- Automatically delete reports older than XX days.

Thanks a lot,

**Comment by linhhuynhtruc** [comment]
Hi @kelson-pereira,

Thank you for your suggestions.

Now you can delete multiple results on the Katalon TesOps cloud interface. Please refer to [this document](https://docs.katalon.com/katalon-analytics/docs/project-management-delete.html#delete-an-execution) for details.

In addition, currently, we still do not support deleting multiple results from CLI. We will consider it for our future development.

I will close this ticket now. For other bug reports or feature requests, please create a new one.

Cheers,
