### ISSUE TITLE
[Feature] Ability to delete multiple executions at once

### ISSUE THREAD

**Issue by dlopes690** [katalon-studio/katalon-testops#48]
It would be great if we had the ability to delete multiple executions at once through a checkbox select and then apply the same action to all checked fields. This would help clear up a good chunk of reports that were duplicated by #46 instead of going one by one. This could also help for future instances.

**Comment by kelson-pereira** [comment]
Dear @dlopes690,

I hope this issue is the same feature already requested in the issue #24. Could you please verify?

Thank you.

**Comment by linhhuynhtruc** [comment]
Hi @dlopes690,

Thank you for your suggestion.

This feature is now available in Katalon TestOps. Please refer to [this document](https://docs.katalon.com/katalon-analytics/docs/project-management-delete.html#delete-an-execution) for more details.

Cheers,
