### ISSUE TITLE
[Feature] Bulk delete of test results

### ISSUE THREAD

**Issue by chimanfu** [katalon-studio/katalon-testops#67]
the current single delete result feature is not convenient and not working some time. Need an option to delete multiple results from the project.

**Comment by MartinB134** [comment]
I totally agree. I have already 880 listings, that I will never be able to delete. Also an Option to delete tests, that are older than xdays/ older than a certain Date would be super nice.

**Comment by Padoplin** [comment]
Hello everyone!

We've already put this in our product backlog. Meanwhile, stay tuned!

Regards,

Padoplin

**Comment by linhhuynhtruc** [comment]
Hi all,

Thank you for your suggestions.

This feature is now available in Katalon TestOps. Please refer to [this document](https://docs.katalon.com/katalon-analytics/docs/project-management-delete.html#delete-an-execution) for more details.

Cheers,
