### ISSUE TITLE
[Feature] Notification email sent to the user who launches the test

### ISSUE THREAD

**Issue by Nilton-github** [katalon-studio/katalon-testops#69]
Hi Katalon team,
First of all, thank you! You do a great job.

The feature I would like to have would be to have the possibility to configure a project to send the notification email at the end of a test only to the user who launches the test. Email would be sent to the email address associated with the user Katalon account. It will be nice to use it in the analytics portal for large teams.

Best regards.
Nilton.

**Comment by Dwgthomson** [comment]
I am not sure if I should create a separate feature request, but if you could also filter these to only send if there was a failed test, rather than just any test, that would be awesome.

**Comment by Oxybul** [comment]
Hi Daniel, 
You already can configure it in the project settings, if you d'ont see this feature is because you'll need to update your Katalon studio version to last version.
Regards

**Comment by linhhuynhtruc** [comment]
Hi,

The notification emails will be sent to the users who have already configured the email settings. If other members in your organization do not want to receive those emails, they can disable the settings in TestOps.

I will close this ticket now. If you have any other feature requests or bug reports, feel free to create a new ticket.

Thank you.


> Hi Daniel,
> You already can configure it in the project settings, if you d'ont see this feature is because you'll need to update your Katalon studio version to last version.
> Regards

Hi Nilton,

It's possible to receive only notification emails of failed executions. Please go to TestOps and update your configure your settings.

Thank you.
