### ISSUE TITLE
[Feature] Ability to Delete Agents

### ISSUE THREAD

**Issue by Dwgthomson** [katalon-studio/katalon-testops#75]
When Looking at the Agents Screen in Katalon Analytics, I can see where I have previously run an agent on another machine, and while troubleshooting that machine I revoked the API key and created a new one for that machine, however now I have realised that I cannot remove the previous version of that box from the list of agents.

If we could get a button to remove these "dead" agents, that would be great!

**Comment by Padoplin** [comment]
Hi @Dwgthomson,

I agree with you that it would be great if users could remove unused agents. Our team considers putting this in our product backlog. Thanks a lot.

Regards,

Padoplin

**Comment by linhhuynhtruc** [comment]
Hi @Dwgthomson,

This feature is now available in Katalon TestOps. To delete agents, please go to your project and select TestOps CI, go to Test Environments to view the list of agents. You can delete the agent if needed.
