### ISSUE TITLE
[Feature] Ability to pull Code Repo from a GitHub Branch / Katalon Analytics GitHub integration

### ISSUE THREAD

**Issue by Dwgthomson** [katalon-studio/katalon-testops#76]
Hi Currently I can pull from the latest branch on my machine, zip up the repository locally, and then upload that zip folder to the Code Repo in Katalon Analytics.

However It would be awesome to have built in integration with GitHub, so that I could point Katalon to a specific branch of my repository (and ideally include the option to have a sub folder to point to), and use that as the Code Repo for the Grid tests that I assign to my Agents.

By having this added, it would enable me to select what branch I want to test with, without the need to download the repository and re-upload it.  It would also enable me to run these tests from devices that do not have the storage space to first download the branch I want to run the tests from.

I have been enjoying exploring Katalon Analytics, and look forward to seeing how it progresses.

Thanks
Daniel.

**Comment by Padoplin** [comment]
Hello @Dwgthomson,

We're appreciative of your suggestion. We consider putting this in our product backlog. Thanks a lot.

Regards,

Padoplin

**Comment by linhhuynhtruc** [comment]
Hi @Dwgthomson,

This feature is now available in Katalon TestOps. Please refer to [this document](https://docs.katalon.com/katalon-analytics/docs/git-test-project.html) for more details.

Thank you.
