### ISSUE TITLE
[Feature] Donwload all files to .zip file

### ISSUE THREAD

**Issue by anuskka23** [katalon-studio/katalon-testops#77]
Hi
I want to can donwload all execution´s files to a .zip/.rar file 
It´s this possible?

Thanks
Regards
Ana

**Comment by Padoplin** [comment]
Hi there,

Sorry that currently, Katalon Analytics does not support downloading all files of execution at once. 
I will consider putting this request in our backlog. Since we have many tickets from users in the queue, it might take time. 

Kind regards,

Padoplin.

**Comment by linhhuynhtruc** [comment]
Hi @anuskka23,

Thanks for your suggestion.

Now you can download multiple executions as .zip files. Please refer to [this document](https://docs.katalon.com/katalon-analytics/docs/download-test-results.html#download-multiple-executions-as-a-zip-file) for more details.

Cheers,
