### ISSUE TITLE
Run comparison 

### ISSUE THREAD

**Issue by engmostafasamir** [katalon-studio/katalon-testops#79]
Hello, 

I would like to suggest adding new feature by which the user can compare between two (or many) different runs by showing the status of each test case in each run.

**Comment by linhhuynhtruc** [comment]
Hi @engmostafasamir,

Thanks for your suggestion.

This feature is now available in Katalon TestOps. Please visit [here](https://docs.katalon.com/katalon-analytics/docs/compare-test-results.html) for the document.
