### ISSUE TITLE
[Bug] Test Execution Never ends. Marking complete will remove data

### ISSUE THREAD

**Issue by somedumbfox** [katalon-studio/katalon-testops#80]
- Katalon Studio Version: 6.3.3
- OS Version: Windows Datacenter 2012
- Browser Version: Chrome

Steps to Reproduce:

Infinite Test Execution is random. Out of all tests suites I've completed, I've had a less than 5% chance of this happening.

When a test suite fails to report that the execution has ended, there is a bug that removes the test case results count.

1. Select the hamburger menu by the Test suite that is still running, but complete.
2. Select Mark as Completed and continue the prompts.

Expected behavior: 
The test suite is marked as complete, and current passed/failed/error/incomplete counts remain untouched. The name of the test suite being executed is saved. And the current run time is saved.

Actual behavior:
The test case is marked as completed, all counts are set to zero, the name of the test suite is set to blank, and the run time is set to zero.

Screenshots:
![Capture](https://user-images.githubusercontent.com/22248602/65534545-aafed480-decd-11e9-88ce-e7eca69682b9.PNG)
Test 27 and 28 are the same test and should be displaying similar data.

**Comment by somedumbfox** [comment]
First time it happened twice in a row. I verified the test has finish on the local machine and is no longer sending data to Katalon Analytics. However the test suite still shows as running.
![Capture](https://user-images.githubusercontent.com/22248602/65538773-0df46980-ded6-11e9-8bac-9ce220b8b274.PNG)

**Comment by pgkanaris** [comment]
I too am experiencing this issue. Also when this occurs and you select Mark Complete all results are deleted. I have also tried to re-import the results which does not upload the values.

**Comment by Padoplin** [comment]
Hi all,

These fields are empty and keep loading if there are no files uploaded to Katalon Analytics from Katalon Studio. Katalon Studio only uploads test results when the executions have already finished.

Please double-check if there are any uploaded files in those executions.

Regards,

Jass

**Comment by somedumbfox** [comment]
When this does occur, the katalon logs suggest that the upload is done and the test is finished. I'll paste in the entire log when it does occur again.

Overall, I have found that the test will actually hang anywhere from about half an hour to an hour before being marked completed on its own. After that it seems to be fine. However, it you do try to mark the test complete before it's resolved on it's own, all data is lost.

So the short term solution is just to leave it alone and let it resolve on it's own. It's not something that's documented that can happen, and just looks to be a handshake problem between the client and the server and eventually a time out allows the process to be completed.

**Comment by pgkanaris** [comment]
Hi Juan,

Thank you for your response on this issue. I thought there would be a timeout, but unfortunately my test collections never time out and therefore are not marked complete. Do you happen to know the timeout limit?

Paul

**Comment by pgkanaris** [comment]
Hi Padoplin,

Yes there are files to be uploaded. Katalon Studio Enterprise Version 7 beta reports the files have uploaded.

Thank you,
Paul

**Comment by somedumbfox** [comment]
@pgkanaris There isn't a time out documented. So that's a question the devs could answer. In my experience, it's anywhere between half an hour, to one hour. Mainly because I'm not watching the test suites like a hawk, I just leave it be and come back later.

**Comment by Maott** [comment]
I'm facing the same problem right now.
Earlier today and in the last days uploading reports worked fine.

Report seems to be successfully uploaded to Analytics, but the spinner is not stopping.

This is what I can see in the Travis log (Reflects as Test 66 in the screenshot below)

```
Copying report to folder /katalon/katalon/source/report...
Uploading report to Katalon Analytics...
Start sending test result to Katalon Analytics
Uploading log files in folder path: /tmp/katalon_execute/project/Reports/20191010_102120/Test/20191010_102120
Sending file: /tmp/katalon_execute/project/Reports/20191010_102120/Test/20191010_102120/execution.uuid
KA: Start uploading report to KA server: https://analytics.katalon.com
Sending file: /tmp/katalon_execute/project/Reports/20191010_102120/Test/20191010_102120/execution0.log
KA: Start uploading report to KA server: https://analytics.katalon.com
Sending file: /tmp/katalon_execute/project/Reports/20191010_102120/Test/20191010_102120/execution.properties
KA: Start uploading report to KA server: https://analytics.katalon.com
Katalon Analytics - Execution URL: https://analytics.katalon.com/from-ks/execution-result?teamId=21813&projectId=28008&id=4149314
End sending to Katalon Analytics
Report has been sent to Katalon Analytics
--------------------------------------------------------------------------------
Test Suites/Test - Chrome - 20191010_102120............................1/1(100%)
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
Test Suites/Test - Chrome - 20191010_102120............................1/1(100%)
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
Test Suites/Test - Chrome - 20191010_102120............................1/1(100%)
```

In Katalon Analytics it looks like this:
![image](https://user-images.githubusercontent.com/26432296/66567680-08e71980-eb68-11e9-939f-236bac475fb8.png)

Marking the test as completed also deletes all results, like in test 64.

**Comment by somedumbfox** [comment]
@Maott The only fix so far, from my experience, is to allow Analytics to time out the upload. It can take more than half an hour to time out server side. As long as you don't mark the test complete, it will not delete the data already uploaded.

Marking the test complete during this phase will delete the data. You are the third person to confirm this bug so far. At least I'm not alone!

**Comment by somedumbfox** [comment]
closed the issue by mistake.

**Comment by Maott** [comment]
@somedumbfox 
The problem didn't occur again for me since last friday.
Does it still occur for you?

**Comment by somedumbfox** [comment]
@Maott Due to holiday release planning, I haven't been able to use Katalon in general. It's currently on my backlog after Holidays are over.

As I have mentioned before. It occurs at random, and is never consistent. So the steps to reliably reproduce the bug is unknown.

**Comment by pgkanaris** [comment]
Hi Juan,

I agree I have seen the issue occur at random over the past couple of months. To date, I do not have a reliable way to reproduce the issue, either. I am currently running some test and will keep you updated.

Thank you,
Paul

**Comment by GeraldoJuniorBr** [comment]
Is there already a forecast for correcting the error, or some form of correction without waiting for the time limit?

**Comment by clifmo** [comment]
This happens consistently for me. It happens in a headless collection where as other test suites in the same project do not have this issue. 12 hours later it still hasn't timed out. Executions from 3 days ago still have not timed out. 

The execution ran, testops upload completed. The only abnormality in the logs is this message, for which nothing turns up on the Google machine: **NLS missing message: ConsoleMain_MSG_NON_DEVOPS_LICENSE_COMPATIBLITY in: com.kms.katalon.execution.constants.executionMessages**

**Comment by jimsears** [comment]
I reported this bug on the Katalon forum. The developer says it was fixed but it is still broken for me.

https://forum.katalon.com/t/testops-executions-re-import-removes-test-results/50051/9

**Comment by jimsears** [comment]
Hi, I've been attempting to get an update on this issue and came across 4 similar issues. All the other issues don't have a recent update either. At the risk of spamming each bug with these details, I'm going to mention the similar bugs in hopes of getting an update on this issue and maybe merging this issue into one. Lastly, the common thread in this problem is that it doesn't always fail. Issue 137 states there is an issue with the API upload using AWS and the response was error code 500. 

My goal is to get an update please. Ty!

https://github.com/katalon-studio/katalon-testops/issues/80
https://github.com/katalon-studio/katalon-testops/issues/108
https://github.com/katalon-studio/katalon-testops/issues/137
https://github.com/katalon-studio/katalon-testops/issues/144

**Comment by jimsears** [comment]
FYI to those interested or following this issue
- I opened a support case with Katalon since I'm a paying customer and I've been told version 8.0.5 will have the fix for uploading results.

**Comment by jimsears** [comment]
Hi all,

KS 8.0.5 has fixed two issues with report upload. 
1) Special characters causing null pointer exception 
2) Loading reports into TestOps.
It seems to work for me but I would be interested to know if you still have issues.

~Jim
